version: "3"

services:
  db:
    #image: mariadb:latest
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: doli
      MYSQL_USER: doli
      MYSQL_DATABASE: dolibarr
    volumes:
      - data-mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - '0.0.0.0:13306:3306'    
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password


  dolibarr:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: db
      DOLI_DB_USER: doli
      DOLI_DB_PASSWORD: doli
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: 'http://0.0.0.0'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
      - "80:80"
        
  ontop:
    image: ontop/ontop-endpoint:4.1.0
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/OCELERP.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/OCELERP.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/ERPOrder.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/ERPOrder.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      - ./demo:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
      [
          "/opt/wait-for-it/wait-for-it.sh",
          "db:3306",
          "--timeout=0",
          "--strict",
          "--",
          "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "${SERVER_PORT}:8080"        
#    links:
#      - mariadb
volumes:
  data-mysql: { }